### ISSUE TITLE
module 'bpy.utils' has no attribute 'previews'

### ISSUE THREAD

**Issue by Cinabutts** [haseebahmed295/Noise-Nodes#6]
brand new fresh install of Blender 4.4 with factory settings on windows 10.

`Exception in module register(): C:\Users\Joey's PC\AppData\Roaming\Blender Foundation\Blender\4.4\extensions\blender_org\noise_nodes\__init__.py
Error: module 'bpy.utils' has no attribute 'previews'
Exception in module register(): C:\Users\Joey's PC\AppData\Roaming\Blender Foundation\Blender\4.4\extensions\blender_org\noise_nodes\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.4\4.4\scripts\modules\addon_utils.py", line 515, in enable
    mod.register()
  File "C:\Users\Joey's PC\AppData\Roaming\Blender Foundation\Blender\4.4\extensions\blender_org\noise_nodes\__init__.py", line 149, in register
    icons = register_icons()
            ^^^^^^^^^^^^^^^^
  File "C:\Users\Joey's PC\AppData\Roaming\Blender Foundation\Blender\4.4\extensions\blender_org\noise_nodes\__init__.py", line 125, in register_icons
    icons = bpy.utils.previews.new()
            ^^^^^^^^^^^^^^^^^^
AttributeError: module 'bpy.utils' has no attribute 'previews'`

It refuses to enable.

**Comment by Cinabutts** [comment]
okay nvm idk why but this time when i exited blender and came back it works fine but still but my point is i keep having this error happen so if possible could you add some checks within the addon? i clearly don't know how to code lol

**Comment by haseebahmed295** [comment]
Actually this issue has already been fixed in latest version on GitHub

**Comment by Cinabutts** [comment]
well it continues to be an issue, idk what i did this time i been just trying to get a clean reinstall of blender 4.4 and ensure all my addons work without error, i just reinstalled blender 4.4 after uninstalling with Absolute Uninstaller then deleted the 4.4 folder leftover in the AppData Roaming blender folder finally i reinstalled blender via the msi installer on their site and again ensured i have 0 errors before i then added solely this addon and the issue persists. please let me know how i can help lol

**Comment by Cinabutts** [comment]
Im trying to figure out whats going on myself, the newest version of the addon 4.0 works fine on my other blender installs (4.3.2 & 4.2) but doesn't on 4.4. im so confused here.. and i know obviously the last version works fine but without the previews i just need to figure out though if it's this addon or if my blender or something somewhere is corrupt

**Comment by Cinabutts** [comment]
jesus christ i swear that said 4.0 last time i checked. my apologies for the spam lmfao 4.1 works fine. Anyway thanks and i salute thee for the addon itself, you are a godsend. have an awesome day!

**Comment by ErlanBazarov** [comment]
I have the same issue in 4.4.0
